name: odinson-entrypoint (scala)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # see https://github.com/actions/setup-java#testing-against-different-java-versions
      matrix:
        distribution: [ 'zulu', 'temurin' ]
        # NOTE: extra (processors v8.4.6) does not work with Java 17
        java: [ '8', '11' ]
    name: Java ${{ matrix.java }} (${{ matrix.distribution }})
    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - name: Run tests
      working-directory: ./odinson-entrypoint
      run: sbt test